name: Node.js CI/CD with Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t mydockerhubuser/node-app:latest .
          docker push mydockerhubuser/node-app:latest

  deploy-to-k8s:
    needs: test-build-and-push
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/node-app-deployment node-app=mydockerhubuser/node-app:latest
          kubectl rollout status deployment/node-app-deployment
